// Generated by Gargl (https://github.com/jodoglevy/gargl) using triviacrack.gtf
// This module requires jQuery. In Node.JS, jsdom and xmlhttprequest are also required.

try {
	// Enable module to work with jQuery in Node.JS
	var jsdom = require('jsdom');
	var window = jsdom.jsdom().createWindow();
	var XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;

	var $ = require('jquery')(window);
	$.support.cors = true;
	$.ajaxSettings.xhr = function() {
		return new XMLHttpRequest;
	}
}
catch(e) {
	console.log(e);
}

var TriviaCrack = {};


TriviaCrack.GetUserData = function (UserID, TimestampInMilliseconds, callback) {
	var type = 'GET';

	var headers = {
		"Accept-Language": "en-US,en;q=0.8",
		"Host": "api.preguntados.com",
		"Referer": "https://preguntados.com/game/",
		"Accept-Encoding": "gzip, deflate, sdch",
		"User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36",
		"Eter-Session": "ap_session=undefined",
		"Origin": "https://preguntados.com",
		"Connection": "keep-alive",
		"Accept": "application/json, text/javascript, */*; q=0.01",
		"Content-Type": "application/json; charset=utf-8",
		"Eter-Agent": "1|Web-FB|Chrome 39.0.2171.65|0|Windows|0|1.1||en||1",
		"etergames-referer": "true",
	};

	var queryString = "?" + "_" + "=" + encodeURIComponent(TimestampInMilliseconds) + "&";

	var data = "";

	var url = "https://api.preguntados.com/api/users/" + UserID + queryString;

	$.ajax({
		type: type,
		url: url,
		headers: headers,
		data: data,
		beforeSend: function(xmlHttpRequest) {
			// Requires node-XMLHttpRequest version 1.5.1 or later to set some headers in Node.js
			if(xmlHttpRequest.setDisableHeaderCheck) xmlHttpRequest.setDisableHeaderCheck(true);
			return true;
		}
	})
	.always(
		function (response, error) {
			response = response || '';

			if (!response.responseText) {
				try {
					var $html = $(toStaticHTML(response));
				}
				catch(e) {
					var $html = $(response);
				}
			}
			else response = response.responseText;

			var fullResponse = {
				response: response,
			};

			callback(null, fullResponse);

		}
	);
};
if(typeof(exports) != "undefined") exports.GetUserData = TriviaCrack.GetUserData; // For nodeJS

TriviaCrack.GetProducts = function (TimestampInMilliseconds, callback) {
	var type = 'GET';

	var headers = {
		"Accept-Language": "en-US,en;q=0.8",
		"Host": "api.preguntados.com",
		"Referer": "https://preguntados.com/game/",
		"Accept-Encoding": "gzip, deflate, sdch",
		"User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36",
		"Eter-Session": "ap_session=undefined",
		"Origin": "https://preguntados.com",
		"Connection": "keep-alive",
		"Accept": "application/json, text/javascript, */*; q=0.01",
		"Content-Type": "application/json; charset=utf-8",
		"Eter-Agent": "1|Web-FB|Chrome 39.0.2171.65|0|Windows|0|1.1|en|en||1",
		"etergames-referer": "true",
	};

	var queryString = "?" + "market_type" + "=" + encodeURIComponent("FACEBOOK") + "&" + "_" + "=" + encodeURIComponent(TimestampInMilliseconds) + "&";

	var data = "";

	var url = "https://api.preguntados.com/api/products" + queryString;

	$.ajax({
		type: type,
		url: url,
		headers: headers,
		data: data,
		beforeSend: function(xmlHttpRequest) {
			// Requires node-XMLHttpRequest version 1.5.1 or later to set some headers in Node.js
			if(xmlHttpRequest.setDisableHeaderCheck) xmlHttpRequest.setDisableHeaderCheck(true);
			return true;
		}
	})
	.always(
		function (response, error) {
			response = response || '';

			if (!response.responseText) {
				try {
					var $html = $(toStaticHTML(response));
				}
				catch(e) {
					var $html = $(response);
				}
			}
			else response = response.responseText;

			var fullResponse = {
				response: response,
			};

			callback(null, fullResponse);

		}
	);
};
if(typeof(exports) != "undefined") exports.GetProducts = TriviaCrack.GetProducts; // For nodeJS

TriviaCrack.GetDashboard = function (UserID, TimestampInMilliseconds, callback) {
	var type = 'GET';

	var headers = {
		"Accept-Language": "en-US,en;q=0.8",
		"Host": "api.preguntados.com",
		"Referer": "https://preguntados.com/game/",
		"Accept-Encoding": "gzip, deflate, sdch",
		"User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36",
		"Eter-Session": "ap_session=undefined",
		"Origin": "https://preguntados.com",
		"Connection": "keep-alive",
		"Accept": "application/json, text/javascript, */*; q=0.01",
		"Content-Type": "application/json; charset=utf-8",
		"Eter-Agent": "1|Web-FB|Chrome 39.0.2171.65|0|Windows|0|1.1|en|en||1",
		"etergames-referer": "true",
	};

	var queryString = "?" + "app_config_version" + "=" + encodeURIComponent("1418500689") + "&" + "_" + "=" + encodeURIComponent(TimestampInMilliseconds) + "&";

	var data = "";

	var url = "https://api.preguntados.com/api/users/" + UserID + "/dashboard" + queryString;

	$.ajax({
		type: type,
		url: url,
		headers: headers,
		data: data,
		beforeSend: function(xmlHttpRequest) {
			// Requires node-XMLHttpRequest version 1.5.1 or later to set some headers in Node.js
			if(xmlHttpRequest.setDisableHeaderCheck) xmlHttpRequest.setDisableHeaderCheck(true);
			return true;
		}
	})
	.always(
		function (response, error) {
			response = response || '';

			if (!response.responseText) {
				try {
					var $html = $(toStaticHTML(response));
				}
				catch(e) {
					var $html = $(response);
				}
			}
			else response = response.responseText;

			var fullResponse = {
				response: response,
			};

			callback(null, fullResponse);

		}
	);
};
if(typeof(exports) != "undefined") exports.GetDashboard = TriviaCrack.GetDashboard; // For nodeJS

TriviaCrack.GetGameData = function (GameID, UserID, TimestampInMilliseconds, callback) {
	var type = 'GET';

	var headers = {
		"Accept-Language": "en-US,en;q=0.8",
		"Host": "api.preguntados.com",
		"Referer": "https://preguntados.com/game/",
		"Accept-Encoding": "gzip, deflate, sdch",
		"User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36",
		"Eter-Session": "ap_session=undefined",
		"Origin": "https://preguntados.com",
		"Connection": "keep-alive",
		"Accept": "application/json, text/javascript, */*; q=0.01",
		"Content-Type": "application/json; charset=utf-8",
		"Eter-Agent": "1|Web-FB|Chrome 39.0.2171.65|0|Windows|0|1.1|en|en||1",
		"etergames-referer": "true",
	};

	var queryString = "?" + "_" + "=" + encodeURIComponent(TimestampInMilliseconds) + "&";

	var data = "";

	var url = "https://api.preguntados.com/api/users/" + UserID + "/games/" + GameID + queryString;

	$.ajax({
		type: type,
		url: url,
		headers: headers,
		data: data,
		beforeSend: function(xmlHttpRequest) {
			// Requires node-XMLHttpRequest version 1.5.1 or later to set some headers in Node.js
			if(xmlHttpRequest.setDisableHeaderCheck) xmlHttpRequest.setDisableHeaderCheck(true);
			return true;
		}
	})
	.always(
		function (response, error) {
			response = response || '';

			if (!response.responseText) {
				try {
					var $html = $(toStaticHTML(response));
				}
				catch(e) {
					var $html = $(response);
				}
			}
			else response = response.responseText;

			var fullResponse = {
				response: response,
			};

			callback(null, fullResponse);

		}
	);
};
if(typeof(exports) != "undefined") exports.GetGameData = TriviaCrack.GetGameData; // For nodeJS

